version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./tmp/images/:/tmp/images/
    tty: true
    depends_on:
      - redis
    environment:
      - "REDIS_HOST=redis:6379"

  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server