name: Linux Container Node Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: cheeseapi.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t cheeseapi.azurecr.io/cheeseapi:${{ github.sha }}
        docker push cheeseapi.azurecr.io/cheeseapi:${{ github.sha }}

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'cheeseapi'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'cheeseapi.azurecr.io/cheeseapi:${{ github.sha }}'
